// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK0NJsUZ6m3S3yAzbVpF8b3QT08hCDXMo',
    appId: '1:923853633921:web:a7506d530dccc832a31080',
    messagingSenderId: '923853633921',
    projectId: 'trinetra-8eabf',
    authDomain: 'trinetra-8eabf.firebaseapp.com',
    databaseURL: 'https://trinetra-8eabf.firebaseio.com',
    storageBucket: 'trinetra-8eabf.firebasestorage.app',
    measurementId: 'G-ABC123DEF456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0NJsUZ6m3S3yAzbVpF8b3QT08hCDXMo',
    appId: '1:923853633921:android:a7506d530dccc832a31080',
    messagingSenderId: '923853633921',
    projectId: 'trinetra-8eabf',
    storageBucket: 'trinetra-8eabf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0NJsUZ6m3S3yAzbVpF8b3QT08hCDXMo',
    appId: '1:923853633921:ios:a7506d530dccc832a31080',
    messagingSenderId: '923853633921',
    projectId: 'trinetra-8eabf',
    storageBucket: 'trinetra-8eabf.firebasestorage.app',
    iosBundleId: 'com.example.trinetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0NJsUZ6m3S3yAzbVpF8b3QT08hCDXMo',
    appId: '1:923853633921:macos:a7506d530dccc832a31080',
    messagingSenderId: '923853633921',
    projectId: 'trinetra-8eabf',
    storageBucket: 'trinetra-8eabf.firebasestorage.app',
    iosBundleId: 'com.example.trinetra',
  );
}
